# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PART_1_and_2

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd client'
- task: Docker@2
  inputs:
    containerRegistry: 'nairobi'
    repository: 'memories_frontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cd server'
    
- task: Docker@2
  inputs:
    containerRegistry: 'nairobi'
    repository: 'memories_backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/manifests'
    ArtifactName: 'manifests'

    
    
